T_task: 20.0

N_task: 10
peg_ee_offset: 0.08

hole_pose:
  pos: [0.5, 0, 0.425]
  quat: [1.0, 0.0, 0.0, 0.0]
  height: 0.1
  pertubation:
    xy_std: 0.00
    z_std: 0.00
    angle_std_deg: 0.0

    #xy_std: 0.005
    #z_std: 0.001
    #angle_std_deg: 1.0

devices:
  arm:
    max_linear_vel: 0.05
    max_angular_vel: 0.2

episode:
  approach:
    quat:  [0, 1, 0, 0]
    pos_threshold: 0.01
    hover_height: 0.05
    speed_transit: 0.3
    speed_descent: 0.05
    success_threshold: 0.05
    pertubation:
      xy_std: 0.00
      z_std: 0.00
      angle_std_deg: 0.0

  contact:
    force_threshold: 2.0    # N, when to consider surface touched
    f_push: 4.0
    timeout: 5.0
    n_confirm: 100

  search:
    hole_detection_threshold: 0.001
    timeout: 40
    wiggle:
      a: [8.0, 8.0, 4.931, 0.766, 0.906, 3.228]
      f:   [2.179, 1.561, 0.0,   0.718, 0.720, 0.143]
      phi: [-0.078, 0.776, 0.0, -1.562, 0.610, -0.119]
      az:  4.931